name: Pipeline de treinamento ML

on:
  push:
    branches:
      - main
    paths:
      - 'src/models/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'poetry.lock'
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'backend/**'
  #     - 'frontend/**'
  #     - 'k8s/**'
  repository_dispatch:
    types:
      - anomalia-detectada-retreinar

env:
  PYTHON_VERSION: '3.10'

jobs:
  anomalia-detect:
    runs-on: ubuntu-latest
    steps:
      - name: Recebendo o payload do Webhook
        run: |
          echo "Evento recebido de fora do Github!"
          echo "Motivo do disparo: ${{ github.event.client_payload.motivo }}"
          echo "Acurácia atual reportada: ${{ github.event.client_payload.acuracia }}"

      - name: Iniciar Retreinamento
        run: echo "Iniciando download dos dados novos e acionando instancias com GPU"

  preparando-dados:
    needs: anomalia-detect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install poetry
        run: pip install poetry

      - name: Install python version ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      
      - name: Install dependencies - Poetry
        run: poetry install

      - name: Rodar ETL (preparar-dados)
        run: poetry run python src/models/preparar-dados.py

      - name: Salvar dataset como artefato
        uses: actions/upload-artifact@v7
        with:
          name: dataset
          path: dataset_processado.csv
  treinamento:
    needs: preparando-dados
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download do artefato
        uses: actions/download-artifact@v7
        with:
          name: dataset

      - name: Verificar download artifact
        run: |
          echo "Conteúdo do diretório atual:"
          ls -la
          echo "Lendo as primeiras linhas do CSV chamado dataset:"
          cat dataset_processado.csv

      - name: Executar batalha (Champion vs Challenger)
        run: python scripts/avaliar_desafiante.py

      - name: Ler o relatório Markdown
        id: relatorio
        run: |
          conteudo=$(cat relatorio_pr.md)
          echo "BODY_PR<<EOF" >> $GITHUB_ENV
          echo "$conteudo" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Criar pull request automático
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[BOT] Novo modelo treinado - atualização de arquitetura"
          title: "Atualização do modelo de fraude (Challenger venceu)"
          body: ${{ env.BODY_PR }}
          branch: "auto-update-modelo"
          base: "main"
          labels: "mlops, automated-pr, machine-learning"


      